spring.application.name=stockfeed

spring.jackson.mapper.accept_case_insensitive_properties=false

spring.mongodb.uri=${MONGODB_URL_STOCK}
spring.mongodb.database=stock
spring.mongodb.auto-index-creation=true 

# Feed Provider Configuration
feed-provider.wsUrl=${WS_URL}
feed-provider.key=${API_KEY}
feed-provider.keyName=${API_KEY_HEADER}
feed-provider.secret=${API_SECRET}
feed-provider.secretName=${API_SECRET_HEADER}
feed-provider.tickers=${TICKERS}

management.endpoint.health.show-details=always
