spring.application.name=stockfeed

spring.jackson.mapper.accept_case_insensitive_properties=false

spring.mongodb.uri=${MONGODB_URL_STOCK}
spring.mongodb.database=stock
spring.mongodb.auto-index-creation=true 

# Feed Provider Configuration
feed-provider.wsUrl=${WS_URL}
feed-provider.key=${API_KEY}
feed-provider.keyName=${API_KEY_HEADER}
feed-provider.secret=${API_SECRET}
feed-provider.secretName=${API_SECRET_HEADER}
feed-provider.tickers=${TICKERS}

management.endpoint.health.show-details=always

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# OpenTelemetry
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
management.otlp.metrics.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/metrics}
management.otlp.logging.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/logs}
management.tracing.sampling.probability=1.0

# Export metrics via OTLP
management.metrics.export.otlp.enabled=true
management.metrics.export.otlp.step=30s

# Export logs via OTLP
logging.exporter.otlp.enabled=true
